spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/db-auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

jwt:
    secret: "hellopethellopethellopethellopethellopethellopethellopethellopethellopethellopethellopet"
    access-expiration: 90000
    refresh-expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0